
    ##################################################
    ###   Visit https://github.com/tinybirdco/ci   ###
    ###   for more details or custom CI/CD         ###
    ##################################################

    name: Tinybird k2a_workshop - CD Workflow

    on:
      workflow_dispatch:
      push:
        branches:
          - main
          - master
        paths:
          - 'tinybird/**'
    jobs:
      cd:  # deploy changes to workspace 'k2a_workshop'
        uses: tinybirdco/ci/.github/workflows/cd.yml@v3.1.0
        with:
          data_project_dir: tinybird
        secrets:
          tb_admin_token: ${{ secrets.TB_K2A_WORKSHOP_ADMIN_TOKEN }}  # set the Workspace admin token in GitHub secrets
          tb_host: https://ui.us-east.tinybird.co
